version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      ci-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "[ci]"
    labels:
      - maintenance
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "[c++]"
    labels:
      - maintenance
