version: 4.5.0.99.{build}

image: Visual Studio 2015
platform: x86
configuration:
  - '3.8'

# only build on 'master' and pull requests targeting it
branches:
  only:
    - master
    - ci/test

environment:
  matrix:
    - COMPILER: MINGW
      TASK: python
      BUILD: 43

clone_depth: 1

build: false

install:
  - set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  - set PYTHON_VERSION=%CONFIGURATION%

test_script:
  - ps: |
      powershell.exe -ExecutionPolicy Bypass -File $env:APPVEYOR_BUILD_FOLDER\.ci\test-windows.ps1
