version: 4.5.0.99.{build}

image: Visual Studio 2015
platform: x86
configuration:
  - '3.8'

# only build on 'master' and pull requests targeting it
branches:
  only:
    - master
    - ci/test

environment:
  matrix:
    - COMPILER: MINGW
      TASK: python
      BUILD: 42

clone_depth: 1

build: false

install:
  - set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  - set PYTHON_VERSION=%CONFIGURATION%
  - "&'C:\Program Files\Git\usr\bin\bash.exe' -c 'export ALLOW_SKIP_ARROW_TESTS=1'"
      # export APPVEYOR="true"
      # export CMAKE_BUILD_PARALLEL_LEVEL=4
      # export MINICONDA="C:\Miniconda3-x64"
      # export PATH="$MINICONDA;$MINICONDA\Scripts;$PATH"
      # export BUILD_SOURCESDIRECTORY="$APPVEYOR_BUILD_FOLDER"

test_script:
  - sh: |
      echo $BUILD
      conda config --remove channels defaults
      conda config --add channels nodefaults
      conda config --add channels conda-forge
      conda config --set channel_priority strict
      conda init sh
      sh.exe - %APPVEYOR_BUILD_FOLDER%\.ci\test-windows.ps1
