stages:
  - build
  - test

default:
  image: willianz/lightgbm-build-env:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - make install
    - cd ../
    - cd python-package
    - python setup.py install
    - cd -
  artifacts:
    paths:
      - /opt/conda/lib/*/site-packages/lightgbm
    untracked: false
    expire_in: 1 days

test-sample:
  stage: test
  script:
    - cd .ci/regression/sample
    - bash ../verify_result.sh

test-bin-example:
  stage: test
  script:
    - cd .ci/regression/dataset_from_examples
    - bash ../verify_result.sh

