stages:
  - build
  - test

default:
  image: buildpack-deps:bionic

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - make install
    - cd ../

test-sample:
  stage: test
  script:
    - cd .ci/regression/sample
    - bash ../verify_result.sh
