stages:
  - build
  - test

default:
  image: willianz/lightgbm-build-env:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - make install
    - cd ../
    - cd python-package
    - python setup.py install
    - cd -
  artifacts:
    untracked: true
    expire_in: 1 days

.before_tests:
  before_script:
    - pip install -e python-package

test-sample:
  extends: .before_tests
  stage: test
  script:
    - cd .ci/regression/sample
    - bash ../verify_result.sh

test-bin-example:
  extends: .before_tests  
  stage: test
  script:
    - cd .ci/regression/dataset_from_examples
    - bash ../verify_result.sh

