version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-23.11"
conda:
  environment: docs/env.yml
formats:
  - pdf
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
submodules:
  include: all
  recursive: true
