FROM daskdev/dask:latest

RUN apt update && \
    apt-get install -y \
        build-essential \
        cmake

COPY . /opt/LightGBM

RUN conda install -y -c conda-forge \
    dask-cloudprovider \
    scikit-learn \
    numpy \
    pandas && \
    pip install \
        awscli && \
    # install LightGBM
    cd /opt/LightGBM/python-package && \
    python setup.py sdist && \
    pip install dist/lightgbm*.tar.gz && \
    conda clean --all
