FROM ubuntu:22.04

ENV \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

ARG LIGHTGBM_GIT_REF=stable

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        build-essential \
        git \
        libomp-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L -o cmake.sh https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-linux-$(arch).sh && \
    chmod +x cmake.sh && \
    sh ./cmake.sh --prefix=/usr/local --skip-license && \
    rm cmake.sh

RUN git clone \
        --recursive \
        https://github.com/Microsoft/LightGBM && \
    git -C ./LightGBM checkout ${LIGHTGBM_GIT_REF} && \
    cd ./LightGBM && \
    cmake -B build -S . && \
    cmake --build build -j4 && \
    cmake --install build && \
    cd .. && \
    rm -rf ./LightGBM

ENTRYPOINT ["lightgbm"]
