FROM rocker/verse:latest

WORKDIR /lgbm

# R
RUN apt-get update && \
    apt-get install -y build-essential && \
    git clone --recursive --branch stable --depth 1 https://github.com/Microsoft/LightGBM && \
    cd LightGBM && \
    Rscript build_r.R
