FROM ubuntu:24.04

ARG CONDA_DIR=/opt/miniforge
ARG LIGHTGBM_GIT_REF=stable
ARG LIGHTGBM_GIT_URL=https://github.com/Microsoft/LightGBM.git

ENV \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=$CONDA_DIR/bin:$PATH

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        git \
        libomp-dev && \
    # python environment
    curl -sL https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-$(arch).sh -o miniforge.sh && \
    /bin/bash miniforge.sh -f -b -p $CONDA_DIR && \
    conda config --set always_yes yes --set changeps1 no && \
    # lightgbm
    conda install -q -y numpy pandas scipy scikit-learn && \
    git clone \
        --recursive \
        "${LIGHTGBM_GIT_URL}" && \
    git -C ./LightGBM checkout ${LIGHTGBM_GIT_REF} && \
    cd ./LightGBM && \
    sh ./build-python.sh install && \
    # clean
    apt-get autoremove -y && apt-get clean && \
    conda clean -a -y && \
    cd .. && \
    rm -rf ./LightGBM
