FROM ubuntu:24.04

ARG LIGHTGBM_GIT_REF=stable
ARG LIGHTGBM_GIT_URL=https://github.com/Microsoft/LightGBM.git

ENV \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        git \
        libomp-dev && \
    rm -rf /var/lib/apt/lists/*

RUN git clone \
        --recursive \
        "${LIGHTGBM_GIT_URL}" && \
    git -C ./LightGBM checkout ${LIGHTGBM_GIT_REF} && \
    cd ./LightGBM && \
    cmake -B build -S . && \
    cmake --build build -j4 && \
    cmake --install build && \
    cd .. && \
    rm -rf ./LightGBM

ENTRYPOINT ["lightgbm"]
