verbose = "info"
no_progress = false
cache = false
scheme = ["http", "https", "file"]
include_fragments = true
no_ignore = true
insecure = true
require_https = true
accept = ["100..=103", "200..=299"]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
retry_wait_time = 5

#[filtering]
#ignore=
#  pythonapi/lightgbm\..*\.html.*
#  http.*amd.com/.*
#  https.*dl.acm.org/doi/.*
#  https.*tandfonline.com/.*
