verbose = "info"
no_progress = false
cache = false
scheme = ["http", "https", "file"]
include_mail = false
no_ignore = true
insecure = false
require_https = true
accept = ["100..=103", "200..=299"]
user_agent = "curl/7.88.1"
timeout = 60
retry_wait_time = 10
max_concurrency = 10
