verbose = "info"
no-progress = false
cache = false
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
insecure = true
#recursionlevel=1
#anchors=1

#[filtering]
#ignore=
#  pythonapi/lightgbm\..*\.html.*
#  http.*amd.com/.*
#  https.*dl.acm.org/doi/.*
#  https.*tandfonline.com/.*
#ignorewarnings=http-redirected,http-robots-denied,https-certificate-error
#checkextern=1

#[AnchorCheck]
