name: Distributed test

on:
  push:
    branches: [tests/distributed]

defaults:
  run:
    shell: bash -l {0}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Compile binary
        run: |
          conda install -c conda-forge cxx-compiler cmake make pytest numpy scikit-learn
          mkdir build && cd build
          cmake .. && make -j2

      - name: run tests
        run: |
          cp lightgbm tests/distributed/
          cd python-package/ && python setup.py install --precompile
          cd ../tests/distributed && pytest test_distributed.py
