name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cpu:
    name: build (CPU)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: dockerfile-cli (build)
        run: |
          docker build \
            -t lightgbm:cli \
            --build-arg LIGHTGBM_GIT_REF=${{ github.head_ref }} \
            --build-arg LIGHTGBM_GIT_URL=https://github.com/${{ github.repository }} \
            - < ./docker/dockerfile-cli
      - name: dockerfile-cli (test)
        run: |
          docker run \
            --entrypoint="" \
            --rm \
            lightgbm:cli \
            which lightgbm
      - name: dockerfile-r (build)
        run: |
          docker build \
            -t lightgbm:r \
            --build-arg LIGHTGBM_GIT_REF=${{ github.head_ref }} \
            --build-arg LIGHTGBM_GIT_URL=https://github.com/${{ github.repository }} \
            - < ./docker/dockerfile-r
      - name: dockerfile-r (test)
        run: |
          docker run \
            --rm \
            lightgbm:r \
            Rscript -e "library(lightgbm); print(sessionInfo())"
      - name: dockerfile-python (build)
        run: |
          docker build \
            -t lightgbm:python \
            --build-arg LIGHTGBM_GIT_REF=${{ github.head_ref }} \
            --build-arg LIGHTGBM_GIT_URL=https://github.com/${{ github.repository }} \
            - < ./docker/dockerfile-python
      - name: dockerfile-python (test)
        run: |
          docker run \
            --rm \
            lightgbm:python \
            python -c "import lightgbm; print(f'lightgbm version: {lightgbm.__version__}')"
  build-gpu:
    name: build (GPU)
    runs-on: LightGBM-GPU
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: dockerfile.gpu (build)
        run: |
          docker build \
            -t lightgbm:gpu \
            --build-arg LIGHTGBM_GIT_REF=${{ github.head_ref }} \
            --build-arg LIGHTGBM_GIT_URL=https://github.com/${{ github.repository }} \
            - < ./docker/gpu/dockerfile.gpu
      - name: dockerfile-cli-only.gpu (build)
        run: |
          docker build \
            -t lightgbm:cli-only.gpu
            --build-arg LIGHTGBM_GIT_REF=${{ github.head_ref }} \
            --build-arg LIGHTGBM_GIT_URL=https://github.com/${{ github.repository }} \
            - < ./docker/gpu/dockerfile-cli-only.gpu
      - name: dockerfile-cli-only.gpu (test)
        run: |
          docker run \
            --entrypoint="" \
            --rm \
            lightgbm:cli-only.gpu \
            which lightgbm
      - name: dockerfile-cli-only-distroless.gpu (build)
        run: |
          docker build \
            -t lightgbm:cli-only-distroless.gpu \
            --build-arg LIGHTGBM_GIT_REF=${{ github.head_ref }} \
            --build-arg LIGHTGBM_GIT_URL=https://github.com/${{ github.repository }} \
            - < ./docker/gpu/dockerfile-cli-only-distroless.gpu
      - name: dockerfile-cli-only-distroless.gpu (test)
        run: |
          docker run \
            --entrypoint="" \
            --rm \
            lightgbm:cli-only-distroless.gpu \
            which lightgbm
  all-docker-jobs-successful:
    if: always()
    runs-on: ubuntu-latest
    needs: [build-cpu, build-gpu]
    steps:
      - name: Note that all tests succeeded
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
