name: GitHub Actions

on: [push]

jobs:
  test:
    name: ${{ matrix.task }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-latest
          #   task: r-package
          # - os: macOS-latest
          #   task: r-package
          - os: windows-latest
            task: r-package
            compiler: MINGW
          # - os: ubuntu-latest
          #   task: lint
        # exclude:
        #   - os: macOS-latest
        #     task: lint
        #   - os: windows-latest
        #     task: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup and run tests on Linux and macOS
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          export HOME_DIRECTORY="$HOME"
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          if [[ "${{ matrix.os }}" == "macOS-latest" ]]; then
              export OS_NAME="macos"
              export COMPILER="gcc"
              export R_MAC_VERSION=3.6.3
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              export OS_NAME="linux"
              export COMPILER="clang"
              export R_TRAVIS_LINUX_VERSION=3.6.3-1bionic;
          fi
          if [ -z ${{ matrix.compiler }} ]; then
              export COMPILER=${{ matrix.compiler }}
          fi
          export TASK="${{ matrix.task }}"
          export HOME_DIRECTORY="$HOME"
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          if [[ "${{ matrix.os }}" == "macOS-latest" ]]; then
              export OS_NAME="macos"
              export COMPILER="gcc"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              export OS_NAME="linux"
              export COMPILER="clang"
          fi
          export GITHUB_ACTIONS="true"
          export CONDA="$HOME/miniconda"
          export PATH="$CONDA/bin:${HOME}/.local/bin:$PATH"
          export CONDA_ENV="test-env"
          export LGB_VER=$(head -n 1 VERSION.txt)
          export AMDAPPSDK_PATH=$HOME/AMDAPPSDK
          export LD_LIBRARY_PATH="$AMDAPPSDK_PATH/lib/x86_64:$LD_LIBRARY_PATH"
          $GITHUB_WORKSPACE/.ci/setup.sh
          $GITHUB_WORKSPACE/.ci/test.sh
      # # reference: https://github.com/marketplace/actions/setup-conda
      # - name: Use conda on Windows
      #   if: matrix.os == 'windows-latest'
      #   uses: s-weigand/setup-conda@v1
      #   with:
      #     activate-conda: true
      #  https://github.com/marketplace/actions/setup-miniconda
      - name: Use conda on Windows
        if: matrix.os == 'windows-latest'
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: false
      - name: conda init powershell
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: conda init powershell
      - name: Setup and run tests on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        env:
          GITHUB_ACTIONS: "true"
          TASK: "r-package"
        run: |
          powershell.exe -ExecutionPolicy Bypass -File %GITHUB_WORKSPACE%/.ci/test_windows.ps1

# links
# * https://github.com/microsoft/LightGBM/issues/2353
# *  https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
# * https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
# * https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
# * https://github.com/marketplace/actions/setup-miniconda
# * https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
# * https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md
# * 
