name: Python-package

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  COMPILER: gcc
  CONDA_ENV: test-env
  GITHUB_ACTIONS: 'true'
  OS_NAME: 'macOS-latest'

jobs:
  test:
    name: ${{ matrix.os }}, ${{ matrix.compiler }}, Python ${{ matrix.python_version }}
    runs-on: macOS-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: regular
            python_version: 3.7
          - task: sdist
            python_version: 3.8
          - task: bdist
            python_version: 3.8
          - task: if-else
            python_version: 3.8
          - task: mpi
            method: source
            python_version: 3.8
          - task: mpi
            method: pip
            python_version: 3.7
          - task: mpi
            method: wheel
            python_version: 3.7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5
          submodules: true
      - name: Setup and run tests
        shell: bash
        run: |
          export TASK="${{ matrix.task }}"
          export METHOD="${{ matrix.method }}"
          export COMPILER="${{ matrix.compiler }}"
          export PYTHON_VERSION="${{ matrix.python_version }}"
          export AMDAPPSDK_PATH=$HOME/AMDAPPSDK
          export LD_LIBRARY_PATH="$AMDAPPSDK_PATH/lib/x86_64:$LD_LIBRARY_PATH"
          export LD_LIBRARY_PATH="/usr/local/clang/lib:$LD_LIBRARY_PATH"  # fix error "libomp.so: cannot open shared object file: No such file or directory" on Linux with Clang
          export OPENCL_VENDOR_PATH=$AMDAPPSDK_PATH/etc/OpenCL/vendors
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          export LGB_VER=$(head -n 1 VERSION.txt)
          export CONDA=${HOME}/miniconda
          export PATH=${CONDA}/bin:${PATH}
          $GITHUB_WORKSPACE/.ci/setup.sh || exit -1
          $GITHUB_WORKSPACE/.ci/test.sh || exit -1
  all-successful:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Note that all tests succeeded
      run: echo "🎉"
