name: R reverse dependency checks

on:
  push:
  # Run manually by clicking a button in the UI
  workflow_dispatch:
  # Run on the 5th day of every month
  schedule:
    - cron: '0 0 5 * *'

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # parallelize compilation (extra important for Linux, where CRAN doesn't supply pre-compiled binaries)
  MAKEFLAGS: "-j4"
  # ignore R CMD CHECK NOTE checking how long it has
  # been since the last submission
  _R_CHECK_CRAN_INCOMING_REMOTE_: 0
  # CRAN ignores the "installed size is too large" NOTE,
  # so our CI can too. Setting to a large value here just
  # to catch extreme problems
  _R_CHECK_PKG_SIZES_THRESHOLD_: 100

jobs:
  test:
    name: r-revdepchecks (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install tinytex
        if: startsWith(matrix.os, 'windows')
        uses: r-lib/actions/setup-tinytex@v2
        env:
          CTAN_MIRROR: https://ctan.math.illinois.edu/systems/win32/miktex
          TINYTEX_INSTALLER: TinyTeX
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'
      - name: install system dependencies
        run: |
          brew install libomp
      - name: build package
        run: |
          sh ./build-cran-package.sh
      - name: run revdepchecks
        run: |
          bash ./.ci/run-revdep-checks.sh
      - name: Setup and run tests on Windows
        if: startsWith(matrix.os, 'windows')
        shell: pwsh -command ". {0}"
        run: |
          $env:BUILD_SOURCESDIRECTORY = $env:GITHUB_WORKSPACE
          $env:LGB_VER = (Get-Content -TotalCount 1 $env:BUILD_SOURCESDIRECTORY\VERSION.txt).trim().replace('rc', '-')
          $env:TOOLCHAIN = "${{ matrix.toolchain }}"
          $env:R_VERSION = "${{ matrix.r_version }}"
          $env:R_BUILD_TYPE = "${{ matrix.build_type }}"
          $env:COMPILER = "${{ matrix.compiler }}"
          $env:TASK = "${{ matrix.task }}"
          & "$env:GITHUB_WORKSPACE/.ci/test-windows.ps1"
  test-r-sanitizers:
    name: r-sanitizers (ubuntu-latest, R-devel, ${{ matrix.compiler }} ASAN/UBSAN)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: wch1/r-debug
    strategy:
      fail-fast: false
      matrix:
        include:
          - r_customization: san
            compiler: gcc
          - r_customization: csan
            compiler: clang
    steps:
      - name: Trust git cloning LightGBM
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          RDscript${{ matrix.r_customization }} -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl', 'testthat'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
          sh build-cran-package.sh --r-executable=RD${{ matrix.r_customization }}
          RD${{ matrix.r_customization }} CMD INSTALL lightgbm_*.tar.gz || exit 1
      - name: Run tests with sanitizers
        shell: bash
        run: |
          cd R-package/tests
          exit_code=0
          RDscript${{ matrix.r_customization }} testthat.R >> tests.log 2>&1 || exit_code=-1
          cat ./tests.log
          exit ${exit_code}
  test-r-extra-checks:
    name: r-package (${{ matrix.image }}, R-devel)
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        # references:
        #   * CRAN "additional checks": https://cran.r-project.org/web/checks/check_issue_kinds.html
        #   * images: https://r-hub.github.io/containers/containers.html
        image:
          - clang16
          - clang17
          - clang18
          - clang19
          - gcc14
          - intel
          - rchk
    runs-on: ubuntu-latest
    container: ghcr.io/r-hub/containers/${{ matrix.image }}:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install LaTeX
        shell: bash
        run: |
          if type -f apt 2>&1 > /dev/null; then
            apt-get update
            apt-get install --no-install-recommends -y \
                devscripts \
                texinfo \
                texlive-latex-extra \
                texlive-latex-recommended \
                texlive-fonts-recommended \
                texlive-fonts-extra \
                tidy \
                qpdf
          else
            yum update -y
            yum install -y \
                devscripts \
                qpdf \
                texinfo \
                texinfo-tex \
                texlive-latex \
                tidy
          fi
      - name: Install packages and run tests
        shell: bash
        run: |
          Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
          sh build-cran-package.sh

          # 'rchk' isn't run through 'R CMD check', use the approach documented at
          # https://r-hub.github.io/containers/local.html
          if [[ "${{ matrix.image }}" =~ "rchk" ]]; then
            r-check "$(pwd)" \
            | tee ./rchk-logs.txt 2>&1

            # the '-v' exceptions below are from R/rchk itself and not LightGBM:
            # https://github.com/kalibera/rchk/issues/22#issuecomment-656036156
            if grep -E '\[PB\]|ERROR' ./rchk-logs.txt \
               | grep -v 'too many states' \
               > /dev/null; \
            then
                echo "rchk found issues"
                exit 1
            else
                echo "rchk did not find any issues"
                exit 0
            fi
          fi

          # 'testthat' is not needed by 'rchk', so avoid installing it until here
          Rscript -e "install.packages('testthat', repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"

          if [[ "${{ matrix.image }}" =~ "clang" ]]; then
            # allowing the following NOTEs (produced by default in the clang images):
            #
            #   * checking compilation flags used ... NOTE
            #       Compilation used the following non-portable flag(s):
            #       ‘-Wp,-D_FORTIFY_SOURCE=3’
            #
            # even though CRAN itself sets that:
            # https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-clang
            #
            declare -i allowed_notes=1
          else
            declare -i allowed_notes=0
          fi

          bash .ci/run-r-cmd-check.sh \
            "$(echo lightgbm_$(head -1 VERSION.txt).tar.gz)" \
            "${allowed_notes}"
  all-r-package-jobs-successful:
    if: always()
    runs-on: ubuntu-latest
    needs: [test, test-r-sanitizers, test-r-extra-checks]
    steps:
    - name: Note that all tests succeeded
      uses: re-actors/alls-green@v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
