# contains tests that can run without compiling LightGBM, like
# linters and documentation checks.
name: Static Analysis

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CONDA_ENV: test-env
  GITHUB_ACTIONS: 'true'
  PYTHON_VERSION: 3.8

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: lint
          - task: check-docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5
          submodules: true
      - name: Setup and run tests
        shell: bash
        run: |
          export TASK="${{ matrix.task }}"
          export OS_NAME="linux"
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          export LGB_VER=$(head -n 1 VERSION.txt)
          export CONDA=${HOME}/miniconda
          export PATH=${CONDA}/bin:$HOME/.local/bin:${PATH}
          $GITHUB_WORKSPACE/.ci/setup.sh
          $GITHUB_WORKSPACE/.ci/test.sh
  all-successful:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Note that all tests succeeded
      run: echo "🎉"
